version: '3.7'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root
      MYSQL_DATABASE: bank-system-dev
      MYSQL_USER: mysql-admin
      MYSQL_PASSWORD: mysql-admin-pass
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
